version: '3.6'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: veterinaria
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1s
      timeout: 1s
      retries: 60
  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password

volumes:
  mysql-vol:
